{% set name = "photutils" %}
{% set version = "0.4.1" %}
{% set hash_type = "sha256" %}
{% set hash_value = "8bbb9d298db4e9322abe4f4737e4e39d4822305f3e554e0f09ae8ecc82a23ce1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --offline --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - numpy        # [not (win and py36)]
    - numpy         # [win and py36]
    - cython
  run:
    - python
    - astropy
    - {{ pin_compatible('numpy') }}
    - six

test:
  imports:
    - photutils
    - photutils.aperture
    - photutils.background
    - photutils.centroids
    - photutils.datasets
    - photutils.detection
    - photutils.extern
    - photutils.geometry
    - photutils.isophote
    - photutils.morphology
    - photutils.psf
    - photutils.psf.matching
    - photutils.segmentation
    - photutils.utils

about:
  home: http://photutils.readthedocs.io/
  license: BSD 3-clause
  license_family: BSD
  license_file: ''
  summary: An Astropy package for photometry
  description: |
    Photutils is an Astropy affiliated package to provide tools for detecting
    and performing photometry of astronomical sources.  It is an open source
    (BSD licensed) Python package.  Contributions welcome!
  doc_url: https://photutils.readthedocs.io/
  dev_url: https://github.com/astropy/photutils

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - larrybradley
