appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: aLleQ2MjHdz7Cp76MNn5ZkRhDNM02O+yFQZOoTII9W6pEzyoHEgVRNpBbxoqtNnltKBAigk9OPTftxWQbbH1Dmz1SBXJMFK4AzNGrTcEWtpB2G+ElRceDVqglQhdODPO+Yxiuh5XLlwktK1wJqJOpzttI3T/VfIp5KcGSqrI2cfV0rJoaCu011Q59GHourOT11/4MnQnwFsyEJlf6rnAPs+52hG5VuPdB84HobJXeDab0UMH2EoPjEzOiThI+uH+1Xu3KycWCh4UuB400mMoVnDEjFXYMnbscZjglArP3aB0GVjq1qo86A+OCJXdSSsjhvstn3DoGgcl0LF6w5iA7jlNse5d+x+trIxpKNnzumygyNuLjBmLKKkXsTqA6kawp08C/Y08joqwd6jG75GtHVjfGOaNh3KNJsi1yvJXI+c4FHsr9CK73TDrB2uPW15qCw35okhiCxoeRX3WSbEedxyGjoI05+7OrUdMWGISzZ8uGkwpRtUuMcXyTNmjV4i1pkVYEIvidqDLNSKE+2JIMte915cYKKPpysIxNclysxBjGRY24Ds9OT9Xcc+zmTCdjDx0uA3WobsbsC8Ci+rHfkPv9XBguQdFr3GLygf4B0SiPw4lQxKD95k06Qs3AMqGk9KCsAWStWUwIF17b009zAtoeSCtquDXeqwzOCFwuGo=}
